name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
        experimental: [false]
        include:
          - coverage: --no-coverage
          - php: 7.2
            analysis: true
            coverage: --coverage-clover clover.xml

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1

      - name: Coding standards
        if: matrix.analysis
        run: bin/php-cs-fixer fix --ansi --dry-run --using-cache=no -v --diff

      - name: Static analysis
        if: matrix.analysis
        run: bin/phpstan --memory-limit=1G analyse

      - name: Unit tests
        run: bin/phpunit ${{ matrix.coverage }}

      - name: Refactoring
        if: matrix.analysis
        run: bin/rector --dry-run
